version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      platform: linux/arm64
    image: dialog-bot
    container_name: dialog-bot

    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
